# Path to reference genome and indices.
DNA: '/home/yahmed/NYWWS/reference/nCov_Wuhan.fasta'
INDEX: '/home/yahmed/NYWWS/reference/bwa_ref/nCov_Wuhan.fasta'

GENEXUS_DNA: '/home/yahmed/NYWWS/reference/ion_ampliseq_sars-cov-2-insight.fasta'

# Path to a folder where final files will be written.
OUT_DIR: '/home/yahmed/NYWWS/OUTPUT'

covidRefSequences: '/home/yahmed/NYWWS/reference/GCF_009858895.2_ASM985889v3_genomic.gff'
K2_STD_DB_PATH: '/home/kraken_database'
PRIMER_BED: '/home/primer-schemes/nCoV-2019/V4/SARS-CoV-2.primer.bed'
SCRIPT_DIR: '/home/C-WAP/'
VAR_DEF: '/home/C-WAP/covidRefSequences/varDefinitions.pkl'

## Covid databases
ALL_COVID: '/home/C-WAP/customDBs/allCovidDB/'
MAJOR_COVID: '/home/C-WAP/customDBs/majorCovidDB/'

# Path to a JSON file with samples and their corresponding FASTQ files.
SE_SAMPLES_JSON: '/home/yahmed/NYWWS/samples_se.json'
PE_SAMPLES_JSON: '/home/yahmed/NYWWS/samples_pe.json'

BAMS_DIR: '/home/yahmed/NYWWS/BAM_files/'
