# Path to reference genome and indices.
DNA: 'reference/nCov_Wuhan.fasta'
INDEX: 'reference/bowtie2_ref/nCov_Wuhan'

# Path to a folder where final files will be written.
OUT_DIR: 'Cumulative_Results'
HOME_DIR: './'

covidRefSequences: 'reference/GCF_009858895.2_ASM985889v3_genomic.gff'
SAM_HEADER: 'bam_process/new_header.sam'
SAMPLE_INFO: 'sampling_locations.csv'
R_script: 'scripts/results_summary_outputs.R'

# Path to a JSON file with samples and their corresponding BAM files.
BAM_SAMPLES_JSON: 'samples_bam.json'

BAMS_DIR: 'BAM_DATA/ALL_BAMS/'
