
# Path to reference genome in FASTA format
fasta_ref: "data/reference_genome/2019-nCoV.fasta"

# Path to the folder of BAM samples
bam_folder: "data/raw_bam"

# Path to a table of sample metadata
sample_metadata: "data/sample_metadata/nys-wws-sars2-concentration.csv"

# Path to a header to add to output BAM
bam_header: "data/new_header.sam"

# For a sample to have enough coverage, it must have:
# minimum_fraction of its genome covered at at least minimum_coverage x
minimum_fraction: 0.5
minimum_coverage: 20

# NOT USED SO FAR
# Path to genomic annotation
# covid_refseq: 'data/reference_genome/GCF_009858895.2_ASM985889v3_genomic.gff'

# Path to reference genome and indices.
# INDEX: 'reference/bowtie2_ref/nCov_Wuhan'
# 
# # Path to a folder where final files will be written.
# OUT_DIR: 'Cumulative_Results'
# HOME_DIR: './'
# 
# SAM_HEADER: 'bam_process/new_header.sam'
# SAMPLE_INFO: 'sampling_locations.csv'
# R_script: 'scripts/results_summary_outputs.R'
