
# General
# =======

# Path to reference genome in FASTA format
fasta_ref: "data/reference_genome/2019-nCoV.fasta"

# Path to the folder of BAM samples
bam_folder: "data/raw_bam"

# Path to a table of sample metadata
sample_metadata: "data/sample_metadata/nys-wws-sars2-concentration.csv"

# Path to a header to add to output BAM
bam_header: "data/new_header.sam"

# For a sample to have enough coverage, it must have:
# minimum_fraction of its genome covered at at least minimum_coverage x
minimum_fraction: 0.5
minimum_coverage: 20


# Variant tracking
# ================

BA286_report_threshold: 0.035

# Obsolete parameters, since we're not running variant tracking
# together with the pipeline anymore:

# variants_to_track:
#   - "BA.2.86"
#   - "B.1.2"
#   - "B.1.1.7"
# 
# # What folder to find the groups of mutations we'll track
# mutation_group_folder: "data/variant-mutations"
# 
# # Minimum reads a mutation group should have in a sample to be reported
# min_variant_reads: 6
